### ISSUE TITLE
Docker FROM image not public

### ISSUE THREAD

**Issue by diocles** [OpusVL/OpusVL-FB11#1]
Hello!

I ran "docker build .", but I received this error:

Error: Status 403 trying to pull repository opusvl/perl-5.20-dev

**Comment by Altreus** [comment]
Wow, this languished for a long time. Apologies - I never even noticed we had issues open!

I have made the above image public (it is at quay.io/opusvl/perl-5.20-dev)

Since we have updated the Dockerfile since then, I have also made the new image public.
