### ISSUE TITLE
 Make docker command doesn't work (no access to docker image?)

### ISSUE THREAD

**Issue by jr-duboc** [OpusVL/OpusVL-FB11#69]
When running make docker I get the following:

```
Step 1/34 : FROM quay.io/opusvl/opusvl-perl-base:release-3 AS FB11
unauthorized: access to the requested resource is not authorized
Makefile:20: recipe for target 'docker' failed
```

Seems like I need access to the Docker image, which is restricted. 
Can someone help? Is there an alternative image we can/should use?

**Comment by PaulGWebster** [comment]
Ah we recently moved to using harbor I believe that, that particular image was one of the ones that was moved. I will take a look in the working week should be a simplefix

**Comment by jr-duboc** [comment]
Great, thanks :) 
Any updates on this Docker image?

**Comment by PaulGWebster** [comment]
I have not actually got around to updating the dockerfile for this yet! my apologies, but basically we have moved away from quay and are now hosting our own docker images, fb11 has actually been moved to: 

registry.deploy.opusvl.net/opusvl/fb11-cms:v1-rc17

And will be publicly pull able, as for the perl base I have it on my list to move over and make public as well should not be to long - my apologies for the delay, there are some 300 images in the process of being dealt with :)

**Comment by PaulGWebster** [comment]
Updated dockerfile or this project as of eecdace4e58ffd4421743b69e3fcfd7b879ad344
